name: CI

on:
  push:
    branches:
    - master
  pull_request:
    branches:
    - master
  workflow_dispatch:
    # allow this workflow to be triggered manually

jobs:
  asan:
    name: '[ubuntu] ASan x86_64/ldc-latest'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up D compiler / tools
        uses: dlang-community/setup-dlang@v1.1.0
        with:
          compiler: ldc-latest
      - name: Run unittests
        run: |
          dub test -c asan-unittest --compiler=ldc2

  setup:
    name: 'Load job configuration'
    runs-on: ubuntu-latest
    outputs:
      compilers: ${{ steps.load-config.outputs.compilers }}
    steps:
    - uses: actions/checkout@v2
    - id: load-config
      run: |
        echo "::set-output name=compilers::$(cat .github/workflows/compilers.json | jq -c -M)"

  macos:
    name: '[macos] x86_64/${{ matrix.dc }}'
    runs-on: macos-latest
    needs: setup
    continue-on-error: ${{ contains(matrix.dc, 'beta') || contains(matrix.dc, 'master') }}
    env:
      ARCH: x86_64
    strategy:
      fail-fast: false
      matrix:
        dc: ${{ fromJSON(needs.setup.outputs.compilers) }}
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup D compiler 
        uses: dlang-community/setup-dlang@v1.1.1
        with:
          compiler: ${{ matrix.dc }}
      - name: Test building
        run: dub test --arch=$ARCH --build=unittest-cov
        shell: bash
      - name: Upload coverage data
        uses: codecov/codecov-action@v2

  ubuntu:
    name: '[ubuntu] ${{ matrix.arch }}/${{ matrix.dc }}'
    runs-on: ubuntu-latest
    needs: setup
    continue-on-error: ${{ contains(matrix.dc, 'beta') || contains(matrix.dc, 'master') }}
    env:
      ARCH: ${{ matrix.arch }}
    strategy:
      fail-fast: false
      matrix:
        dc: ${{ fromJSON(needs.setup.outputs.compilers) }}
        arch: [x86, x86_64]
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup D compiler 
        uses: dlang-community/setup-dlang@v1.1.1
        with:
          compiler: ${{ matrix.dc }}
      - name: Install multi-lib for 32-bit systems
        if: matrix.arch == 'x86'
        run: sudo apt-get update && sudo apt-get install gcc-multilib
      - name: Test building
        run: dub test --arch=$ARCH --build=unittest-cov
        shell: bash
      - name: Upload coverage data
        uses: codecov/codecov-action@v2
  
  windows:
    name: '[windows] x86_64/${{ matrix.dc }}'
    runs-on: windows-latest
    needs: setup
    continue-on-error: ${{ contains(matrix.dc, 'beta') || contains(matrix.dc, 'master') }}
    env:
      ARCH: x86_64
    strategy:
      fail-fast: false
      matrix:
        dc: ${{ fromJSON(needs.setup.outputs.compilers) }}
    steps:
      - name: Checkout repo 
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup D compiler 
        uses: dlang-community/setup-dlang@v1.1.1
        with:
          compiler: ${{ matrix.dc }}
      - name: Test building
        run: dub test --arch=$ARCH --build=unittest-cov
        shell: bash
      - name: Upload coverage data
        uses: codecov/codecov-action@v2
